// forge/templates/svelte-frontend-template/template/src/lib/shared/ui/EmptyState.svelte
<script lang="ts">
	import { Package } from 'lucide-svelte';

	let {
		message = 'No items found',
		icon: Icon = Package as any
	}: {
		message?: string;
		icon?: any;
	} = $props();
</script>

<div class="flex flex-col items-center justify-center py-16 text-center">
	<Icon class="h-12 w-12 text-muted-foreground mb-3" />
	<p class="text-sm text-muted-foreground">{message}</p>
</div>

// forge/templates/vue-frontend-template/template/src/shared/components/EmptyState.vue
<script setup lang="ts">
import { Inbox } from 'lucide-vue-next'
import type { Component } from 'vue'

defineProps<{
  message: string
  icon?: Component
}>()
</script>

<template>
  <div class="flex flex-col items-center justify-center gap-4 p-8 text-center">
    <component
      :is="icon || Inbox"
      class="h-16 w-16 text-muted-foreground/50"
    />
    <p class="text-sm text-muted-foreground">{{ message }}</p>
    <slot name="action" />
  </div>
</template>
