// forge/templates/svelte-frontend-template/template/src/lib/shared/ui/HealthIndicator.svelte
<script lang="ts">
	let { status }: { status: string } = $props();

	const variant = $derived(
		status === 'UP' ? 'default' : status === 'DEGRADED' ? 'secondary' : 'destructive'
	);

	const dotColor = $derived(
		status === 'UP'
			? 'bg-emerald-500'
			: status === 'DEGRADED'
				? 'bg-amber-500'
				: status === 'DOWN'
					? 'bg-red-500'
					: 'bg-gray-400'
	);

	const badgeClass = $derived(
		variant === 'default'
			? 'border-transparent bg-primary text-primary-foreground'
			: variant === 'secondary'
				? 'border-transparent bg-secondary text-secondary-foreground'
				: 'border-transparent bg-destructive text-destructive-foreground'
	);
</script>

<span
	class="inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-xs font-semibold {badgeClass}"
>
	<span class="h-2 w-2 rounded-full {dotColor}"></span>
	{status}
</span>

// forge/templates/vue-frontend-template/template/src/shared/components/HealthIndicator.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Badge } from '@/shared/ui/badge'

const props = defineProps<{
  status: 'UP' | 'DOWN' | 'DEGRADED' | string
}>()

const variant = computed(() => {
  switch (props.status) {
    case 'UP':
      return 'default' as const
    case 'DEGRADED':
      return 'secondary' as const
    case 'DOWN':
      return 'destructive' as const
    default:
      return 'outline' as const
  }
})

const dotColor = computed(() => {
  switch (props.status) {
    case 'UP':
      return 'bg-emerald-500'
    case 'DEGRADED':
      return 'bg-amber-500'
    case 'DOWN':
      return 'bg-red-500'
    default:
      return 'bg-gray-400'
  }
})
</script>

<template>
  <Badge :variant="variant" class="gap-1.5">
    <span :class="['h-2 w-2 rounded-full', dotColor]" />
    {{ status }}
  </Badge>
</template>
