// forge/templates/svelte-frontend-template/template/src/lib/shared/ui/StatusBadge.svelte
<script lang="ts">
	import { CheckCircle, Edit, Archive } from 'lucide-svelte';

	let { status }: { status: string } = $props();

	const config = $derived(
		status === 'ACTIVE'
			? {
					icon: CheckCircle,
					class:
						'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-400'
				}
			: status === 'DRAFT'
				? {
						icon: Edit,
						class: 'bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-400'
					}
				: {
						icon: Archive,
						class: 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400'
					}
	);
</script>

<span
	class="inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-medium {config.class}"
>
	<config.icon class="h-3 w-3" />
	{status}
</span>

// forge/templates/vue-frontend-template/template/src/shared/components/StatusBadge.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Pencil, CheckCircle, Archive } from 'lucide-vue-next'

const props = defineProps<{ status: string }>()

const config = computed(() => {
  switch (props.status) {
    case 'DRAFT':
      return { icon: Pencil, label: 'Draft', color: 'text-orange-600 bg-orange-100 dark:text-orange-400 dark:bg-orange-900/30' }
    case 'ACTIVE':
      return { icon: CheckCircle, label: 'Active', color: 'text-green-600 bg-green-100 dark:text-green-400 dark:bg-green-900/30' }
    case 'ARCHIVED':
      return { icon: Archive, label: 'Archived', color: 'text-gray-600 bg-gray-100 dark:text-gray-400 dark:bg-gray-800/50' }
    default:
      return { icon: Pencil, label: props.status, color: 'text-gray-600 bg-gray-100 dark:text-gray-400 dark:bg-gray-800/50' }
  }
})
</script>

<template>
  <span
    class="inline-flex items-center gap-1.5 rounded-full px-2.5 py-0.5 text-xs font-medium"
    :class="config.color"
  >
    <component :is="config.icon" class="h-3.5 w-3.5" />
    {{ config.label }}
  </span>
</template>
