// forge/templates/vue-frontend-template/template/src/features/ai_chat/ui/AiChatMessage.vue
<script setup lang="ts">
import { Sparkles, User, Wrench } from 'lucide-vue-next'
import { useAuth } from '@/shared/composables/useAuth'

const props = defineProps<{
  message: { id: string; role: string; content: string }
  isStreaming?: boolean
}>()

const { user } = useAuth()
</script>

<template>
  <!-- User message -->
  <div v-if="props.message.role === 'user'" class="flex gap-3 flex-row-reverse">
    <div
      class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary"
    >
      <User class="h-3.5 w-3.5 text-primary-foreground" />
    </div>
    <div class="flex max-w-[80%] flex-col gap-0.5">
      <span class="text-xs font-medium text-primary text-right">
        {{ user?.firstName || 'You' }}
      </span>
      <div class="rounded-2xl bg-primary px-4 py-2.5 text-sm leading-relaxed text-primary-foreground">
        {{ props.message.content }}
      </div>
    </div>
  </div>

  <!-- Assistant message -->
  <div v-else-if="props.message.role === 'assistant'" class="flex gap-3">
    <div
      class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full ai-gradient"
    >
      <Sparkles class="h-3.5 w-3.5 text-white" />
    </div>
    <div class="flex max-w-[80%] flex-col gap-0.5">
      <span class="text-xs font-medium text-ai-from">AI</span>
      <div
        class="rounded-2xl ai-gradient px-4 py-2.5 text-sm leading-relaxed text-white"
        :class="{ 'ai-pulse': props.isStreaming && !props.message.content }"
      >
        <template v-if="props.message.content">
          {{ props.message.content }}<span
            v-if="props.isStreaming"
            class="inline-block w-1.5 h-4 ml-0.5 bg-white/70 animate-pulse align-text-bottom"
          />
        </template>
        <template v-else>
          Thinking...
        </template>
      </div>
    </div>
  </div>

  <!-- Tool message -->
  <div v-else-if="props.message.role === 'tool'" class="flex gap-3">
    <div
      class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-muted"
    >
      <Wrench class="h-3.5 w-3.5 text-muted-foreground" />
    </div>
    <div class="flex max-w-[80%] flex-col gap-0.5">
      <span class="text-xs font-medium text-muted-foreground">Tool</span>
      <div class="rounded-lg border bg-muted/50 px-3 py-2 text-xs text-muted-foreground">
        {{ props.message.content }}
      </div>
    </div>
  </div>

  <!-- Default / unknown role -->
  <div v-else class="flex gap-3">
    <div class="flex max-w-[80%] flex-col gap-0.5 pl-10">
      <div class="text-sm text-muted-foreground">
        {{ props.message.content }}
      </div>
    </div>
  </div>
</template>

// forge/templates/svelte-frontend-template/template/src/lib/features/chat/ui/AiChatMessage.svelte
<script lang="ts">
	import { Bot, User } from 'lucide-svelte';
	import type { ChatMessage } from '$lib/features/chat';
	import { cn } from '$lib/shared/lib/utils';

	let { message }: { message: ChatMessage } = $props();

	const isAssistant = $derived(message.role === 'assistant');
	const timeStr = $derived(
		message.timestamp.toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' })
	);
</script>

<div class={cn('flex gap-3', isAssistant ? '' : 'flex-row-reverse')}>
	{#if isAssistant}
		<div
			class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full"
			style="background: linear-gradient(135deg, hsl(var(--ai-gradient-from)), hsl(var(--ai-gradient-to)))"
		>
			<Bot class="h-4 w-4 text-white" />
		</div>
	{:else}
		<div
			class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-muted text-muted-foreground"
		>
			<User class="h-4 w-4" />
		</div>
	{/if}

	<div
		class={cn(
			'max-w-[85%] rounded-lg px-3 py-2 text-sm leading-[1.6]',
			isAssistant
				? 'bg-ai-surface text-ai-surface-foreground border border-ai-border'
				: 'bg-primary text-primary-foreground'
		)}
	>
		<p class="whitespace-pre-wrap break-words">{message.content}</p>
		<span
			class={cn(
				'mt-1 block text-[10px]',
				isAssistant ? 'text-muted-foreground' : 'text-primary-foreground/70'
			)}
		>
			{timeStr}
		</span>
	</div>
</div>
