// forge/templates/vue-frontend-template/template/src/features/ai_chat/ui/AiChat.vue
<script setup lang="ts">
import { ref, nextTick, watch } from 'vue'
import { useRoute } from 'vue-router'
import { X, Send, Sparkles } from 'lucide-vue-next'
import { Button } from '@/shared/ui/button'
import { useAiChat } from '../composables/useAiChat'
import AiChatMessage from './AiChatMessage.vue'
import AgentStatusBar from './AgentStatusBar.vue'

const route = useRoute()
const {
  messages,
  isGenerating,
  chatContext,
  closeChat,
  sendMessage,
} = useAiChat()

const inputText = ref('')
const messagesContainer = ref<HTMLElement | null>(null)

watch(
  () => route.meta.title,
  (title) => {
    chatContext.value = (title as string) || 'Current Page'
  },
  { immediate: true },
)

function handleSend() {
  const text = inputText.value.trim()
  if (!text || isGenerating.value) return
  sendMessage(text)
  inputText.value = ''
  nextTick(scrollToBottom)
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault()
    handleSend()
  }
}

function scrollToBottom() {
  if (messagesContainer.value) {
    messagesContainer.value.scrollTop = messagesContainer.value.scrollHeight
  }
}

watch(messages, () => nextTick(scrollToBottom), { deep: true })
</script>

<template>
  <aside class="flex h-full flex-col bg-background">
    <!-- Header: AI Assistant + Close -->
    <div class="flex h-14 shrink-0 items-center justify-between border-b px-4">
      <div class="flex items-center gap-2">
        <div class="flex h-7 w-7 items-center justify-center rounded-full ai-gradient">
          <Sparkles class="h-3.5 w-3.5 text-white" />
        </div>
        <span class="text-sm font-medium">AI Assistant</span>
      </div>
      <Button
        variant="ghost"
        size="icon"
        class="h-8 w-8 interactive-press"
        @click="closeChat"
      >
        <X class="h-4 w-4" />
      </Button>
    </div>

    <!-- Messages -->
    <div
      ref="messagesContainer"
      class="flex flex-1 flex-col gap-4 overflow-y-auto p-4"
    >
      <div
        v-if="messages.length === 0 && !isGenerating"
        class="flex flex-1 flex-col items-center justify-center gap-3 text-center"
      >
        <div class="flex h-16 w-16 items-center justify-center rounded-full ai-gradient">
          <Sparkles class="h-8 w-8 text-white" />
        </div>
        <p class="text-sm text-muted-foreground">
          Ask me anything about this page.
        </p>
      </div>

      <AiChatMessage
        v-for="(msg, idx) in messages"
        :key="msg.id"
        :message="msg"
        :is-streaming="isGenerating && msg.role === 'assistant' && idx === messages.length - 1"
      />
    </div>

    <!-- Status bar -->
    <AgentStatusBar />

    <!-- Input -->
    <div class="shrink-0 border-t p-3">
      <div
        class="flex items-end gap-2 rounded-2xl border bg-card p-2 transition-shadow"
        :class="{ 'ai-pulse': isGenerating }"
      >
        <textarea
          v-model="inputText"
          placeholder="Ask anything..."
          rows="1"
          class="flex-1 resize-none bg-transparent py-1 text-sm outline-none placeholder:text-muted-foreground"
          style="max-height: 96px"
          @keydown="handleKeydown"
        />
        <Button
          variant="ghost"
          size="icon"
          class="h-8 w-8 shrink-0 interactive-press"
          :disabled="!inputText.trim() || isGenerating"
          @click="handleSend"
        >
          <Send class="h-4 w-4 text-ai-from" />
        </Button>
      </div>
    </div>
  </aside>
</template>

// forge/templates/svelte-frontend-template/template/src/lib/features/chat/ui/AiChat.svelte
<script lang="ts">
	import { X, MessageCircle } from 'lucide-svelte';
	import { getUiStore } from '$lib/features/shell';
	import { getChatStore } from '$lib/features/chat';
	import AiChatMessage from './AiChatMessage.svelte';
	import AiChatInput from './AiChatInput.svelte';
	import type { ChatMode } from '$lib/features/shell';

	let { mode = 'inline' }: { mode?: ChatMode } = $props();

	const ui = getUiStore();
	const chat = getChatStore();

	let messagesContainer: HTMLDivElement | undefined;
	let chatInputRef: AiChatInput | undefined;

	// Auto-scroll to bottom when new messages arrive
	$effect(() => {
		const _ = chat.messages.length;
		if (messagesContainer) {
			requestAnimationFrame(() => {
				if (messagesContainer) {
					messagesContainer.scrollTop = messagesContainer.scrollHeight;
				}
			});
		}
	});

	// Focus input when chat opens
	$effect(() => {
		if (ui.chatOpen && chatInputRef) {
			setTimeout(() => chatInputRef?.focusInput(), 350);
		}
	});

	function handlePanelKeydown(e: KeyboardEvent) {
		if (e.key === 'Escape') {
			e.preventDefault();
			ui.closeChat();
		}
	}
</script>

<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
<aside
	id="ai-chat-panel"
	class="flex h-full flex-col bg-background border-ai-border"
	aria-label="AI Chat"
	onkeydown={handlePanelKeydown}
>
	<!-- Header -->
	<div class="flex h-14 shrink-0 items-center justify-between border-b border-ai-border px-4">
		<div class="flex items-center gap-2">
			<MessageCircle class="h-4 w-4 text-ai-accent" />
			<span class="text-sm font-semibold">AI Chat</span>
		</div>
		<div class="flex items-center gap-1">
			<span
				class="rounded-full bg-ai-surface px-2.5 py-0.5 text-xs text-ai-surface-foreground"
			>
				{chat.contextLabel}
			</span>
			<button
				class="btn-press rounded-md p-1.5 text-muted-foreground transition-colors hover:bg-accent hover:text-accent-foreground"
				onclick={() => ui.closeChat()}
				aria-label="Close AI Chat"
			>
				<X class="h-4 w-4" />
			</button>
		</div>
	</div>

	<!-- Messages -->
	<div bind:this={messagesContainer} class="flex-1 overflow-y-auto p-4 space-y-4">
		{#if chat.messages.length === 0}
			<div class="flex h-full flex-col items-center justify-center px-6 text-center">
				<div
					class="mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-ai-surface"
				>
					<MessageCircle class="h-6 w-6 text-ai-accent" />
				</div>
				<h3 class="mb-1 text-sm font-medium">How can I help?</h3>
				<p class="text-xs text-muted-foreground">
					Ask a question or describe what you need help with.
				</p>
			</div>
		{:else}
			{#each chat.messages as message (message.id)}
				<AiChatMessage {message} />
			{/each}
			{#if chat.isGenerating}
				<div class="flex items-center gap-2 text-xs text-muted-foreground">
					<div class="flex gap-1">
						<span
							class="h-1.5 w-1.5 rounded-full bg-ai-accent animate-bounce [animation-delay:0ms]"
						></span>
						<span
							class="h-1.5 w-1.5 rounded-full bg-ai-accent animate-bounce [animation-delay:150ms]"
						></span>
						<span
							class="h-1.5 w-1.5 rounded-full bg-ai-accent animate-bounce [animation-delay:300ms]"
						></span>
					</div>
					<span>Thinking...</span>
				</div>
			{/if}
		{/if}
	</div>

	<!-- Input -->
	<AiChatInput bind:this={chatInputRef} />
</aside>
